# Generated by Django 4.2.6 on 2025-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('address_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('road_zip_code', models.CharField(blank=True, max_length=25, null=True)),
                ('road_full_address', models.CharField(blank=True, max_length=500, null=True)),
                ('road_address', models.CharField(blank=True, max_length=500, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('category_1', models.CharField(blank=True, max_length=50, null=True)),
                ('category_2', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name', models.CharField(blank=True, max_length=50, null=True)),
                ('attribute_1', models.CharField(blank=True, max_length=5, null=True)),
                ('attribute_2', models.CharField(blank=True, max_length=5, null=True)),
                ('attribute_3', models.CharField(blank=True, max_length=5, null=True)),
                ('attribute_4', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'food_attribute',
                'managed': False,
            },
        ),
    ]
