# Generated by Django 4.2.6 on 2025-01-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant_new',
        ),
    ]
