# Generated by Django 4.2.6 on 2025-06-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='daegu_restaurants',
        ),
    ]
