# Generated by Django 4.2.6 on 2025-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateRestaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pin_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('pin_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurants_affiliate',
                'managed': False,
            },
        ),
    ]
