# Generated by Django 4.2.6 on 2025-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_image_url', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'foods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCode',
            fields=[
                ('type_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCodeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
            ],
            options={
                'db_table': 'type_code_foods',
                'managed': False,
            },
        ),
    ]
