options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'wouldulike-backend',
        '--source=.',
        '--region=asia-northeast3',  # Cloud Run 리전은 서울 유지
        '--platform=managed',
        '--allow-unauthenticated'
      ]

timeout: 900s
