# Generated by Django 4.2.6 on 2025-09-08 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('SIGNUP', 'Signup'), ('REFERRAL', 'Referral'), ('FLASH', 'FlashDrop')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('rules_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('benefit_json', models.JSONField(default=dict)),
                ('valid_days', models.PositiveIntegerField(default=7)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('QUALIFIED', 'QUALIFIED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=12)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('referee', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='referral_from', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invite_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'ISSUED'), ('REDEEMED', 'REDEEMED'), ('EXPIRED', 'EXPIRED'), ('CANCELED', 'CANCELED')], default='ISSUED', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant_id', models.IntegerField(blank=True, null=True)),
                ('issue_key', models.CharField(blank=True, max_length=120, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupons.campaign')),
                ('coupon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coupons.coupontype')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referrer', 'referee'), name='uq_ref_pair'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('user', 'coupon_type', 'campaign', 'issue_key'), name='uq_coupon_issue_guard'),
        ),
    ]
