# Generated by Django 4.2.6 on 2025-09-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_affiliaterestaurant'),
        ('coupons', '0004_update_coupon_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantpin',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='merchantpin',
            name='restaurant',
            field=models.OneToOneField(blank=True, db_column='restaurant_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_pin', to='restaurants.affiliaterestaurant'),
        ),
    ]
