# Generated by Django 4.2.6 on 2025-10-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_affiliaterestaurant"),
        ("coupons", "0005_remove_merchantpin_restaurant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantCouponBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, default="", max_length=255)),
                ("benefit_json", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_benefits",
                        to="coupons.coupontype",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_benefits",
                        to="restaurants.affiliaterestaurant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("coupon_type", "restaurant"),
                        name="uq_coupon_type_restaurant",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="benefit_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
