# Generated by Django 4.2.6 on 2026-01-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0019_couponrestaurantexclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponrestaurantexclusion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
