# Generated by Django 4.2.6 on 2025-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusMenu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'menus_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampusRestaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'restaurants_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampusRestaurantMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'restaurant_menus_test',
                'managed': False,
            },
        ),
    ]
