# Generated by Django 4.2.6 on 2025-01-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='image',
            field=models.URLField(max_length=400),
        ),
    ]
