# Generated by Django 4.2.6 on 2026-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_trend_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'ordering': ('display_order', '-created_at')},
        ),
    ]
