# Generated by Django 5.1.3 on 2024-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='favorite_restaurants',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, to='guests.restaurant'),
        ),
    ]
