# Generated by Django 5.1.3 on 2024-12-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_restaurant_remove_guestuser_favorite_restaurants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='favorite_restaurants',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='favorite_restaurants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
