# Generated by Django 4.2.6 on 2025-10-12 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0004_guestuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
